-- V050: recomeço das escalas com o editor visual de layouts (decisão do usuário em 30/09/2026).
-- DESTRUTIVA: apaga TODAS as escalas (com celebrações e vagas) e TODOS os layouts de todas as paróquias e recria
-- "Padrão Semanal" e "Padrão Mensal" no formato do editor visual (cabeçalho do documento + linhas da celebração).
-- Não mexe em pessoas, voluntários, indisponibilidades nem inscrições. Não há como desfazer: só rode com backup.

DELETE FROM public.escala_vagas;
DELETE FROM public.escala_eventos;
DELETE FROM public.escalas;
-- O número curto (V038) recomeça em 1: sem a linha do contador, o gatilho começa de novo.
DELETE FROM public.tenant_sequencial WHERE tabela = 'escalas';
DELETE FROM public.layout_escala;

INSERT INTO public.layout_escala (tenant_id, nome, descricao, tipo, colunas, sistema, ativo, padrao)
SELECT id, 'Padrão Semanal', 'Tabela de dias úteis com Acólito Missal, Cruz, Credência, 2 Velas e 2 Sinos.', 'SEMANAL', '[{"idLocal": "c-tit","tipo": "TITULO","escopo": "DOCUMENTO","linha": 0,"coluna": 0,"largura": 12,"conteudo": "#TITULO_ESCALA#","alinhamento": "center","ordem": 1},{"idLocal": "c-sub","tipo": "SUBTITULO","escopo": "DOCUMENTO","linha": 1,"coluna": 0,"largura": 12,"conteudo": "#MES_ANO#","alinhamento": "center","ordem": 2},{"idLocal": "c-dt","tipo": "DATA","escopo": "CELEBRACAO","linha": 0,"coluna": 0,"largura": 2,"conteudo": "#DATA_HORA#","alinhamento": "left","ordem": 3},{"idLocal": "v-mis","tipo": "VAGA","escopo": "CELEBRACAO","linha": 0,"coluna": 1,"largura": 2,"funcao": "MISSAL","posicao": 1,"rotulo": "Acólito Missal","ordem": 4},{"idLocal": "v-crz","tipo": "VAGA","escopo": "CELEBRACAO","linha": 0,"coluna": 2,"largura": 2,"funcao": "CRUZ","posicao": 1,"rotulo": "Cruz","ordem": 5},{"idLocal": "v-crd","tipo": "VAGA","escopo": "CELEBRACAO","linha": 0,"coluna": 3,"largura": 2,"funcao": "CREDENCIA","posicao": 1,"rotulo": "Credência","ordem": 6},{"idLocal": "v-vl1","tipo": "VAGA","escopo": "CELEBRACAO","linha": 0,"coluna": 4,"largura": 1,"funcao": "VELA","posicao": 1,"rotulo": "Vela 1","ordem": 7},{"idLocal": "v-vl2","tipo": "VAGA","escopo": "CELEBRACAO","linha": 0,"coluna": 5,"largura": 1,"funcao": "VELA","posicao": 2,"rotulo": "Vela 2","ordem": 8},{"idLocal": "v-sn1","tipo": "VAGA","escopo": "CELEBRACAO","linha": 0,"coluna": 6,"largura": 1,"funcao": "SINO","posicao": 1,"rotulo": "Sino 1","ordem": 9},{"idLocal": "v-sn2","tipo": "VAGA","escopo": "CELEBRACAO","linha": 0,"coluna": 7,"largura": 1,"funcao": "SINO","posicao": 2,"rotulo": "Sino 2","ordem": 10}]'::jsonb, true, true, true FROM public.tenant;

INSERT INTO public.layout_escala (tenant_id, nome, descricao, tipo, colunas, sistema, ativo, padrao)
SELECT id, 'Padrão Mensal', 'Formato clássico com Missal, Cruz, Credência, 2 Velas, 4 Coletas e 2 Sinos.', 'MENSAL', '[{"idLocal": "c-tit","tipo": "TITULO","escopo": "DOCUMENTO","linha": 0,"coluna": 0,"largura": 12,"conteudo": "#TITULO_ESCALA#","alinhamento": "center","ordem": 1},{"idLocal": "c-sub","tipo": "SUBTITULO","escopo": "DOCUMENTO","linha": 1,"coluna": 0,"largura": 12,"conteudo": "#MES_ANO#","alinhamento": "center","ordem": 2},{"idLocal": "c-dt","tipo": "DATA","escopo": "CELEBRACAO","linha": 0,"coluna": 0,"largura": 12,"conteudo": "#DATA_HORA#","alinhamento": "left","ordem": 3},{"idLocal": "v-mis","tipo": "VAGA","escopo": "CELEBRACAO","linha": 1,"coluna": 0,"largura": 1,"funcao": "MISSAL","posicao": 1,"rotulo": "Acólito Missal","ordem": 4},{"idLocal": "v-crz","tipo": "VAGA","escopo": "CELEBRACAO","linha": 1,"coluna": 1,"largura": 1,"funcao": "CRUZ","posicao": 1,"rotulo": "Cruz","ordem": 5},{"idLocal": "v-crd","tipo": "VAGA","escopo": "CELEBRACAO","linha": 1,"coluna": 2,"largura": 1,"funcao": "CREDENCIA","posicao": 1,"rotulo": "Credência","ordem": 6},{"idLocal": "v-vl1","tipo": "VAGA","escopo": "CELEBRACAO","linha": 1,"coluna": 3,"largura": 1,"funcao": "VELA","posicao": 1,"rotulo": "Vela 1","ordem": 7},{"idLocal": "v-vl2","tipo": "VAGA","escopo": "CELEBRACAO","linha": 2,"coluna": 0,"largura": 1,"funcao": "VELA","posicao": 2,"rotulo": "Vela 2","ordem": 8},{"idLocal": "v-cl1","tipo": "VAGA","escopo": "CELEBRACAO","linha": 2,"coluna": 1,"largura": 1,"funcao": "COLETA","posicao": 1,"rotulo": "Coleta 1","ordem": 9},{"idLocal": "v-cl2","tipo": "VAGA","escopo": "CELEBRACAO","linha": 2,"coluna": 2,"largura": 1,"funcao": "COLETA","posicao": 2,"rotulo": "Coleta 2","ordem": 10},{"idLocal": "v-cl3","tipo": "VAGA","escopo": "CELEBRACAO","linha": 2,"coluna": 3,"largura": 1,"funcao": "COLETA","posicao": 3,"rotulo": "Coleta 3","ordem": 11},{"idLocal": "v-cl4","tipo": "VAGA","escopo": "CELEBRACAO","linha": 3,"coluna": 0,"largura": 1,"funcao": "COLETA","posicao": 4,"rotulo": "Coleta 4","ordem": 12},{"idLocal": "v-sn1","tipo": "VAGA","escopo": "CELEBRACAO","linha": 3,"coluna": 1,"largura": 1,"funcao": "SINO","posicao": 1,"rotulo": "Sino 1","ordem": 13},{"idLocal": "v-sn2","tipo": "VAGA","escopo": "CELEBRACAO","linha": 3,"coluna": 2,"largura": 1,"funcao": "SINO","posicao": 2,"rotulo": "Sino 2","ordem": 14}]'::jsonb, true, true, true FROM public.tenant;
